'''def insert(arr,element):
    arr.append(element)
arr=[10,20,30,40]
key=50
print("before inserting:")
print(arr)
print("after inserting:")
insert(arr,key)
print(arr)'''
'''a=[10,4,10,5,6,4,10]
c=0
n=len(arr)
for i in range(n):
    if a[i]==a[i]+1:
        print()
arr=[10,20,30,40]
key=50
def insert(arr,key)
    arr.append(key)
print(arr)
def insert(arr,key):
    arr.append(key)
arr=[10,20,30,40]
key=50
print("before inserting:")
print(arr)
print("after inserting:")
print(arr)
stack=[]
def push():
    n=int(input("enter the value to insert:"))
    if len(stack)==0:
        stack.append(n)
    else:
        stack.insert(0,n)
    print(n,"is inserted into the satck")
push()
def  
print(stack)'''
class stack:
    def __init__(self):
        self.stack=[]
    def push(self,element):
        self.stack.append(element)
mystack=stack()
mystack.push("a")
mystack.push("b")
mystack.push("c")
print("my stck is ",mystack.stack)



print("------THE END-----")



